#pragma once

enum{
	AF_GODMODE = (1 << 0),
	AF_NO_CLIP = (1 << 1),
	AF_ALWAYSRUN = (1 << 2),
	AF_UNLIMITEDAMMO = (1 << 3),
	AF_RUN_BACKWARD = (1 << 4),
	AF_AUTOPICKUP = (1 << 5),
	AF_PSP = (1 << 6),
	AF_DYNAMIC_MUSIC = (1 << 7),
	AF_GODMODE_RT = (1 << 8),
	AF_COLLISION = (1 << 10),
	AF_RIGHT_SHOULDER = (1 << 11),
	AF_3DSCOPE_ENABLE = (1 << 12),
	AF_PNV_W_SCOPE_DIS = (1 << 13),
	AF_SIMPLE_PDA = (1 << 14),
	AF_3D_PDA = (1 << 15),
	AF_CROUCH_TOGGLE = (1 << 16),
	AF_WPN_ZOOM_OUT_SHOOT = (1 << 17),
	AF_INV_ITEMCONDITION = (1 << 18),
	AF_UNLIMITED_BOLTS = (1 << 19),
	AF_USE_BATTERY = (1 << 20),
	AF_DBG_BATTERY_USE_CONSOLE = (1 << 21),		// for modding, you can see the battery uncharge in console
	AF_USE_FILTERS = (1 << 22),
	ALTERNATIV_ALT_AIM = (1 << 23),
	HUD_ITEM_VOL_LIGHTS = (1 << 24),
	AF_ITEM_ANIMS_ENABLE = (1 << 25),
	AF_NO_HEAD_BOBBING = (1 << 26),
	AF_CMB_SHOW_WEAPON = (1 << 27),
};

enum
{
	AF_LFO_WEATHER_FALLOUT = (1 << 0),
	AF_LFO_HIDE_WEAPON_SAVEZONE = (1 << 1),
	AF_LFO_MASK_BREATH_SOUNDS = (1 << 2),
	AF_LFO_AI_SPAWN_RANDOM = (1 << 3),
	AF_LFO_DYNAMIC_HUD_MASK_OVERLAY = (1 << 4),
	AF_LFO_DYNAMIC_HUD_WPN_SHAKING = (1 << 5),
	AF_LFO_DYNAMIC_HUD_HIT_EFFECTS = (1 << 6),
	AF_HUD_DOF = (1 << 7),
	AF_DEV_MODE = (1 << 8),
	AF_WPN_RELOAD_TYPE = (1 << 9),
	AF_LFO_FREEPLAY = (1 << 10),
	AF_NVG_IDLE_SOUND = (1 << 11),
	AF_ARTEFACT_RESPAWN_FAST = (1 << 12),
	AF_LFO_WEATHER_EXTRA_SNOW_EFFECTS = (1 << 13),
	AF_LFO_WEATHER_EXTRA_EFFECTS = (1 << 14),
	AF_LFO_WEAPON_EXTRA_RECOIL = (1 << 15),
	AF_LFO_ANOMALY_CAM_EFF = (1 << 16),
	AF_LFO_TEST_FLAG = (1 << 17),
	AF_LFO_RW_LOOT = (1 << 18),
	AF_LFO_WEAPON_AIM_CAM_EFF = (1 << 19),
	AF_HUD_ITEM_DOF = (1 << 20),
	AF_LFO_WPN_PH_OBJ = (1 << 21),
	AF_LFO_LEVEL_AUTOSAVES = (1 << 22),
	AF_LFO_DEBUG_HUD_INFOS = (1 << 23),
	AF_LFO_FROSTBITE = (1 << 24),
	AF_LFO_WEATHER_FALLOUT_SIREN = (1 << 25),
	AF_LFO_ECO = (1 << 26),
	AF_LFO_FALLOUT_SLEEP = (1 << 27),
	AF_LFO_NO_AI_MAP_POINTS = (1 << 28),
	//	AF_TAKE_ITEM_ANIMATIONS					= (1<<21),
};

enum
{
	AF_MAINMENU_MUSIC = (1 << 0),
	AF_ALTERNATIV_GLOBAL_MAP = (1 << 1),
	AF_LFO_POSTPROCESS = (1 << 2),
	AF_LFO_PARTICLES = (1 << 3),
	AF_LFO_WPN_DISABLE_WPN_ANIMS = (1 << 4),
	AF_LFO_WPN_MOVEMENT_LAYER = (1 << 5),
	AF_LFO_HUD_FUNCTIONS_ICONS = (1 << 6),
	AF_LFO_SURVIVAL_MODE = (1 << 7),
	AF_LFO_PDA_EXTRA = (1 << 8),
	AF_LFO_SHOT_SHELL_ANIMATIONS = (1 << 9),
	AF_LFO_FULL_MAINMENU = (1 << 10),
	AF_LFO_WEATHER_ICONS = (1 << 11),
	AF_LFO_AMMO_ICONS = (1 << 12),
	AF_LFO_WPN_AIM_RELOADS = (1 << 13),
};

extern Flags32 psActorFlags;
extern Flags32 psActorFlags2;
extern Flags32 psActorFlags3;
extern BOOL		GodMode	();	

extern int		psActorSleepTime;
extern int		psActorQuickSaveNumberCurrent;
extern int		psActorQuickSaveNumberMax;